Config = {}

-- Marketplace Locations (add more as needed)
Config.Locations = {
    {
        name = "Legion Square Market",
        coords = vector3(194.61, -934.12, 30.69),
        ped = {
            model = "s_m_y_shop_mask",
            heading = 180.0,
            coords = vector3(194.61, -934.12, 30.69)
        },
        blip = {
            sprite = 52,
            color = 3,
            scale = 0.8,
            label = "Marketplace"
        }
    },
    {
        name = "Paleto Bay Market",
        coords = vector3(-57.67, 6523.18, 31.49),
        ped = {
            model = "s_m_y_shop_mask",
            heading = 312.06,
            coords = vector3(-57.67, 6523.18, 31.49)
        },
        blip = {
            sprite = 52,
            color = 3,
            scale = 0.8,
            label = "Marketplace"
        }
    }
}

-- Blacklisted items (cannot be listed on marketplace)
Config.BlacklistedItems = {
    "weapon_pistol",
    "weapon_combatpistol",
    "weapon_appistol",
    "weapon_stungun",
    "weapon_pistol50",
    "weapon_snspistol",
    "weapon_heavypistol",
    "weapon_vintagepistol",
    "weapon_marksmanpistol",
    "weapon_revolver",
    "weapon_pistol_mk2",
    "weapon_snspistol_mk2",
    "weapon_revolver_mk2",
    "weapon_doubleaction",
    "weapon_up_atomizer",
    "weapon_ceramicpistol",
    "weapon_navyrevolver",
    "weapon_gadgetpistol",
    "weapon_pericopistol",
    "weapon_microsmg",
    "weapon_smg",
    "weapon_smg_mk2",
    "weapon_assaultsmg",
    "weapon_combatpdw",
    "weapon_machinepistol",
    "weapon_minismg",
    "weapon_raycarbine",
    "weapon_pumpshotgun",
    "weapon_sawnoffshotgun",
    "weapon_assaultshotgun",
    "weapon_bullpupshotgun",
    "weapon_musket",
    "weapon_heavyshotgun",
    "weapon_dbshotgun",
    "weapon_autoshotgun",
    "weapon_pumpshotgun_mk2",
    "weapon_combatshotgun",
    "weapon_assaultrifle",
    "weapon_assaultrifle_mk2",
    "weapon_carbinerifle",
    "weapon_carbinerifle_mk2",
    "weapon_advancedrifle",
    "weapon_specialcarbine",
    "weapon_specialcarbine_mk2",
    "weapon_bullpuprifle",
    "weapon_bullpuprifle_mk2",
    "weapon_compactrifle",
    "weapon_militaryrifle",
    "weapon_heavyrifle",
    "weapon_mg",
    "weapon_combatmg",
    "weapon_combatmg_mk2",
    "weapon_gusenberg",
    "weapon_sniperrifle",
    "weapon_heavysniper",
    "weapon_heavysniper_mk2",
    "weapon_marksmanrifle",
    "weapon_marksmanrifle_mk2",
    "weapon_rpg",
    "weapon_grenadelauncher",
    "weapon_grenadelauncher_smoke",
    "weapon_minigun",
    "weapon_firework",
    "weapon_railgun",
    "weapon_hominglauncher",
    "weapon_compactlauncher",
    "weapon_rayminigun",
    "weapon_emplauncher",
    "weapon_grenade",
    "weapon_bzgas",
    "weapon_molotov",
    "weapon_stickybomb",
    "weapon_proxmine",
    "weapon_snowball",
    "weapon_pipebomb",
    "weapon_ball",
    "weapon_smokegrenade",
    "weapon_flare",
    "weapon_petrolcan",
    "weapon_fireextinguisher",
    "weapon_parachute",
    "weapon_hazardcan",
    "weapon_knife",
    "weapon_nightstick",
    "weapon_hammer",
    "weapon_bat",
    "weapon_golfclub",
    "weapon_crowbar",
    "weapon_bottle",
    "weapon_dagger",
    "weapon_hatchet",
    "weapon_knuckle",
    "weapon_machete",
    "weapon_flashlight",
    "weapon_switchblade",
    "weapon_poolcue",
    "weapon_wrench",
    "weapon_battleaxe",
    "weapon_stone_hatchet",
    "weapon_candycane",
    "weapon_gadgetpistol",
    "weapon_pericopistol",
    "weapon_microsmg",
    "weapon_smg",
    "weapon_smg_mk2",
    "weapon_assaultsmg",
    "weapon_combatpdw",
    "weapon_machinepistol",
    "weapon_minismg",
    "weapon_raycarbine",
    "weapon_pumpshotgun",
    "weapon_sawnoffshotgun",
    "weapon_assaultshotgun",
    "weapon_bullpupshotgun",
    "weapon_musket",
    "weapon_heavyshotgun",
    "weapon_dbshotgun",
    "weapon_autoshotgun",
    "weapon_pumpshotgun_mk2",
    "weapon_combatshotgun",
    "weapon_assaultrifle",
    "weapon_assaultrifle_mk2",
    "weapon_carbinerifle",
    "weapon_carbinerifle_mk2",
    "weapon_advancedrifle",
    "weapon_specialcarbine",
    "weapon_specialcarbine_mk2",
    "weapon_bullpuprifle",
    "weapon_bullpuprifle_mk2",
    "weapon_compactrifle",
    "weapon_militaryrifle",
    "weapon_heavyrifle",
    "weapon_mg",
    "weapon_combatmg",
    "weapon_combatmg_mk2",
    "weapon_gusenberg",
    "weapon_sniperrifle",
    "weapon_heavysniper",
    "weapon_heavysniper_mk2",
    "weapon_marksmanrifle",
    "weapon_marksmanrifle_mk2",
    "weapon_rpg",
    "weapon_grenadelauncher",
    "weapon_grenadelauncher_smoke",
    "weapon_minigun",
    "weapon_firework",
    "weapon_railgun",
    "weapon_hominglauncher",
    "weapon_compactlauncher",
    "weapon_rayminigun",
    "weapon_emplauncher",
    "weapon_grenade",
    "weapon_bzgas",
    "weapon_molotov",
    "weapon_stickybomb",
    "weapon_proxmine",
    "weapon_snowball",
    "weapon_pipebomb",
    "weapon_ball",
    "weapon_smokegrenade",
    "weapon_flare",
    "weapon_petrolcan",
    "weapon_fireextinguisher",
    "weapon_parachute",
    "weapon_hazardcan",
    "weapon_knife",
    "weapon_nightstick",
    "weapon_hammer",
    "weapon_bat",
    "weapon_golfclub",
    "weapon_crowbar",
    "weapon_bottle",
    "weapon_dagger",
    "weapon_hatchet",
    "weapon_knuckle",
    "weapon_machete",
    "weapon_flashlight",
    "weapon_switchblade",
    "weapon_poolcue",
    "weapon_wrench",
    "weapon_battleaxe",
    "weapon_stone_hatchet",
    "weapon_candycane"
}

-- Marketplace Settings
Config.Settings = {
    maxListingsPerPlayer = 20,        -- Maximum active listings per player
    maxBuyOrdersPerPlayer = 10,       -- Maximum active buy orders per player
    minPrice = 1,                      -- Minimum price for items
    maxPrice = 1000000,                -- Maximum price for items
    transactionFeePercent = 2.5,      -- Transaction fee percentage (2.5%)
    refreshInterval = 5000,            -- UI refresh interval in ms (5 seconds)
    enableAnalytics = true            -- Enable analytics tracking
}

-- Interaction Settings (ox_target handles interaction automatically)
Config.Interaction = {
    -- ox_target handles interaction distance and keybinds automatically
}

